name: Update NSE Holidays

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 18 * * *'  # 12:00 AM IST every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_AUTHOR: misterdas

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: python --version
    - run: pip install requests

    - name: Run update script
      run: python update_json.py

    - name: Check git status
      run: git status  # To check if there are changes to commit

    - name: GIT Commit updated nse_holidays.json
      if: contains(fromJson('["schedule", "push", "pull_request"]'), github.event_name)
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "misterdas@users.noreply.github.com"
        git add nse_holidays.json
        git status  # Double-check before committing
        git commit -m "Auto-update NSE holidays: $(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')" || echo "No changes to commit"
        git push
