name: Update NSE Holidays

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 18 * * *'  # 12:00 AM IST every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: "Updated NSE holidays JSON file"
      CI_COMMIT_AUTHOR: misterdas

    steps:
    - uses: actions/checkout@v3

    # Set up Python environment
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x.x'

    # Check Python version
    - run: python --version

    # Install dependencies
    - run: pip install requests

    # Run the update script to fetch and update the JSON file
    - name: Run update script
      run: python update_json.py

    # Commit and push changes if any
    - name: GIT Commit updated nse_holidays.json
      if: contains(fromJson('["schedule", "push", "pull_request"]'), github.event_name)
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "misterdas@users.noreply.github.com"
        git add nse_holidays.json  # Stage the modified file

        # Check if there are any staged changes
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Updated NSE holidays: $(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')"
          git push
        fi
